name: CI

on:
  push:
    paths:
      - "skscope/*.py"
      - "src/**"
      - "pytest/*.py"
      - ".github/workflows/CI.yml"
  pull_request:
    paths:
      - "skscope/*.py"
      - "src/**"
      - "pytest/*.py"
      - ".github/workflows/CI.yml"
  workflow_dispatch:

jobs:
build:
  strategy:
    matrix:
      os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
      python-version: [3.7, 3.8, 3.8, 3.9, 3.10]
  runs-on: ${{ matrix.os }}
  steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install skscope & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade "jax[cpu]"
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        pip install pytest
        pytest pytest -v      
